### ISSUE TITLE
How to run the AIRSIM environment in parallel to implement the A3C algorithm

### ISSUE THREAD

**Issue by robot-xyh** [JacopoPan/a-minimalist-guide#1]
Hello, this project has given me a great help. Your explanation is very detailed and it has brought me a lot of inspiration. I am especially interested in the project combining rllib and airsim. After learning your example, I want to run the airsim environment in parallel, set `num_workers=1 `or2 to increase the sampling speed.
I did this:
Set different json files: json1 and json2.
The settings1.json file set ip=127.0.0.1,
The settings2.json file set ip=127.0.0.2,
When starting the airsim program,
`AirSim.exe --settings'C:\path\to\settings1.json'`
`AirSim.exe --settings'C:\path\to\settings2.json'`
Then I run `minimal-airsim-rllib-ma-env.py`, I found that only the environment corresponding to settings2.json is running, but settings1.json is not running.
I don't know if there are any other changes that need to be made.
If you can give me any help or advice, I am very grateful to you

**Comment by JacopoPan** [comment]
I'm sorry @robot-xyh, I wasn't checking issues on this repo, is this one still open?
